import {useContext, createContext} from 'react'
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { UserContextProvider } from '../context/userContext';
import Header from '../component/Header';
import Auth from '../component/Auth';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserContextProvider>
        {/* <Header /> */}
        <Auth />
      </UserContextProvider>
    </div>
  );
}
